services:
  # Application
  testeducation_api:
    image: testeducation_api:dev
    container_name: testeducation_api
    build:
      context: .
      dockerfile: src/TestEducation.API/Dockerfile     
    ports:
      - "5000:5000"  # HTTP
      - "5001:5001"  # HTTPS
    depends_on:
      - testeducation_database
      - testeducation_minio
      - testeducation_rabbitmq 
    networks:
      - testeducation_network

  # PostgreSQL Database
  testeducation_database:
    image: postgres:latest
    container_name: testeducation_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sherzod3466
      POSTGRES_DB: TestProEducation
    ports:
      - "5432:5432"
    volumes:
      - testeducation_database:/var/lib/postgresql
    networks:
      - testeducation_network
    restart: unless-stopped

  # MinIO Object Storage
  testeducation_minio:
    image: minio/minio
    container_name: testeducation_minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    networks:
      - testeducation_network
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

   # Rabbitmq 
  testeducation_rabbitmq:
    image: rabbitmq:3-management     
    container_name: testeducation_rabbitmq
    environment:
     - RABBITMQ_DEFAULT_USER=guest     
     - RABBITMQ_DEFAULT_PASS=guest  
    networks:
    - testeducation_network
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq
    ports:
    - "5672:5672"  
    - "15672:15672" 

volumes:
  testeducation_database:
    name: testeducation_database
  minio_data:
    name: minio_data
  rabbitmq_data:
    name: rabbitmq_data

    
networks:
  testeducation_network:
    driver: bridge
