services:
  # Application
  testeducation_api:
    image: testeducation_api
    container_name: testeducation_api
    build:
      context: ./src/TestEducation.API
      dockerfile: Dockerfile        
    ports:
      - "5050:5050"
    depends_on:
      - testeducation_database
    networks:
      - testeducation_network

  # PostgreSQL Database
  testeducation_database:
    image: postgres:latest
    container_name: testeducation_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sherzod3466
      POSTGRES_DB: TestProEducation
    ports:
      - "5432:5432"
    volumes:
      - testeducation_database:/var/lib/postgresql
    networks:
      - testeducation_network
    restart: unless-stopped

volumes:
  testeducation_database:
    name: testeducation_database
    
networks:
  testeducation_network:
    driver: bridge
