services:
  testeducation.api:
    image: ${DOCKER_Registry}testeducation.api
    container_name: testeducation.api
    build:
      dockerfile: ./src/TestEducation.API/Dockerfile        
    ports:
      - "5050:5050"


  Postgres:
    image: postgres:15
    container_name: my.postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sherzod3466
      POSTGRES_DB: TestProEducation
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
